project_id = "myvjwpbhdnnrkwazudnh"

[functions.auto-archive-companies]
verify_jwt = false

[functions.notify-new-lead]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.applicant-reminder]
verify_jwt = false
