ALTER TABLE public.applications 
  ADD COLUMN IF NOT EXISTS applicant_updated_at TIMESTAMP WITH TIME ZONE DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS last_viewed_by_employer TIMESTAMP WITH TIME ZONE DEFAULT NULL;